# Generated by Django 4.2.13 on 2024-07-08 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex10', '0003_alter_planets_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
