# Generated by Django 4.2.13 on 2024-06-12 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ex00', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='myMod',
        ),
    ]
