# Generated by Django 4.2.13 on 2024-06-13 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ex00', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
