# Generated by Django 4.2.13 on 2024-07-08 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex09', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planets',
            name='population',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
