# Generated by Django 4.2.13 on 2024-07-08 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex09', '0003_alter_planets_diameter_alter_planets_orbital_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planets',
            name='climate',
            field=models.CharField(null=True),
        ),
    ]
