# Generated by Django 4.2.13 on 2024-07-08 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex09', '0004_alter_planets_climate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planets',
            name='terrain',
            field=models.CharField(null=True),
        ),
    ]
