# Generated by Django 4.2.13 on 2024-07-08 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex09', '0008_alter_people_birth_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='height',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='mass',
            field=models.FloatField(null=True),
        ),
    ]
